### ISSUE TITLE
ICDAR2015检测的问题

### ISSUE THREAD

**Issue by liuwenhaha** [BADBADBADBOY/pytorchOCR#37]
你好，我在训练的时候，ACC一直是0.5，没有变化。请问，可能是哪里出了问题

**Comment by fxwfzsxyq** [comment]
训练了多久，什么backbone




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [BADBADBADBOY/pytorchOCR] ICDAR2015检测的问题 (#37)





 
你好，我在训练的时候，ACC一直是0.5，没有变化。请问，可能是哪里出了问题

**Comment by liuwenhaha** [comment]
> 训练了多久，什么backbone
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月4日(星期五) 下午2:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [BADBADBADBOY/pytorchOCR] ICDAR2015检测的问题 (#37) 你好，我在训练的时候，ACC一直是0.5，没有变化。请问，可能是哪里出了问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/18018760/120757509-35bd2100-c543-11eb-923c-9197239cb28c.png)
刚开始训练，才几个batch，ACC就已经不变化了

**Comment by fxwfzsxyq** [comment]
这是正常的，少则几十，多则100个epoch后才会有变化




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 下午2:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] ICDAR2015检测的问题 (#37)





  
训练了多久，什么backbone
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年6月4日(星期五) 下午2:32 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [BADBADBADBOY/pytorchOCR] ICDAR2015检测的问题 (#37) 你好，我在训练的时候，ACC一直是0.5，没有变化。请问，可能是哪里出了问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  

 刚开始训练，才几个batch，ACC就已经不变化了

**Comment by liuwenhaha** [comment]
> 训练了多久，什么backbone
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月4日(星期五) 下午2:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [BADBADBADBOY/pytorchOCR] ICDAR2015检测的问题 (#37) 你好，我在训练的时候，ACC一直是0.5，没有变化。请问，可能是哪里出了问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

用的是det_DB_mobilev3.yaml，backbone是mbv3_small.old.pth.tar

**Comment by liuwenhaha** [comment]
> 这是正常的，少则几十，多则100个epoch后才会有变化
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月4日(星期五) 下午2:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [BADBADBADBOY/pytorchOCR] ICDAR2015检测的问题 (#37) 训练了多久，什么backbone … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年6月4日(星期五) 下午2:32 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [BADBADBADBOY/pytorchOCR] ICDAR2015检测的问题 (#37) 你好，我在训练的时候，ACC一直是0.5，没有变化。请问，可能是哪里出了问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 刚开始训练，才几个batch，ACC就已经不变化了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

跑了十几分钟，ACC一直是0.5，我就有点慌

**Comment by cqray1990** [comment]
@liuwenhaha 请问你解决了我也是同样的问题

**Comment by yufanxin** [comment]
> 
> 
> @liuwenhaha 请问你解决了我也是同样的问题

我还以为就我是这样，我在自己的数据集上训练了50个epoch（花了将近一下午）也还是0.5，限于电脑性能就没跑了 你增大epoch后acc增加了吗
