### ISSUE TITLE
ICDAR检测

### ISSUE THREAD

**Issue by liuwenhaha** [BADBADBADBOY/pytorchOCR#38]
已经120个epoch了。ACC一直都是0.5，我太慌了啊
![image](https://user-images.githubusercontent.com/18018760/120772706-28a82e00-c553-11eb-8d97-19d4742fef4d.png)

**Comment by liuwenhaha** [comment]
没关系，我还能坚持

**Comment by fxwfzsxyq** [comment]
小模型有时候500个以后变化也有可能，等着吧，之后准确率和iou会很快提升




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 下午4:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [BADBADBADBOY/pytorchOCR] ICDAR检测 (#38)





 
已经120个epoch了。ACC一直都是0.5，我太慌了啊

**Comment by liuwenhaha** [comment]
> 小模型有时候500个以后变化也有可能，等着吧，之后准确率和iou会很快提升
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月4日(星期五) 下午4:37 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [BADBADBADBOY/pytorchOCR] ICDAR检测 (#38) 已经120个epoch了。ACC一直都是0.5，我太慌了啊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

要是500个还不变，我就回家睡觉去了

**Comment by fxwfzsxyq** [comment]
我提供的百度网盘里有我的训练日志，我训练时是170左右的时候变化的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 下午4:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] ICDAR检测 (#38)





  
小模型有时候500个以后变化也有可能，等着吧，之后准确率和iou会很快提升
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年6月4日(星期五) 下午4:37 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [BADBADBADBOY/pytorchOCR] ICDAR检测 (#38) 已经120个epoch了。ACC一直都是0.5，我太慌了啊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
要是500个还不变，我就回家睡觉去了

**Comment by liuwenhaha** [comment]
> 我提供的百度网盘里有我的训练日志，我训练时是170左右的时候变化的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月4日(星期五) 下午4:50 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [BADBADBADBOY/pytorchOCR] ICDAR检测 (#38) 小模型有时候500个以后变化也有可能，等着吧，之后准确率和iou会很快提升 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年6月4日(星期五) 下午4:37 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [BADBADBADBOY/pytorchOCR] ICDAR检测 (#38) 已经120个epoch了。ACC一直都是0.5，我太慌了啊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 要是500个还不变，我就回家睡觉去了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

哦哦，看到log了，哈哈，果然是169epoch的时候突然变化了，谢谢哦

**Comment by cuongngm** [comment]
i was hoping so but by 850 epoch, my iou still 0.5 :(

**Comment by cqray1990** [comment]
@cuongngm 我也是一直0.5总感觉训练有点问题，resnet50也是一样

**Comment by cqray1990** [comment]
@liuwenhaha
