### ISSUE TITLE
test这两个路径下应该是什么样的格式呢？test_file:  和  test_gt_path: 。另外想问下，多分类为什么没有DBProcessTestMLT 的函数，只有DBProcessTest

### ISSUE THREAD

**Issue by aishangmaxiaoming** [BADBADBADBOY/pytorchOCR#46]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/67897601/124691939-3e709080-df0f-11eb-9cb8-08a799e5d244.png">

**Comment by fxwfzsxyq** [comment]
这里在多分类里没有用到，多分类没有去做验证，所以不用管




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [BADBADBADBOY/pytorchOCR] test这两个路径下应该是什么样的格式呢？test_file:  和  test_gt_path: 。另外想问下，多分类为什么没有DBProcessTestMLT 的函数，只有DBProcessTest (#46)

**Comment by fxwfzsxyq** [comment]
对了，你训练的时候要加一个&nbsp; --start_val 把这个值设置成大于你的n_epoch ,这样就不会去做验证

**Comment by aishangmaxiaoming** [comment]
> &nbsp
1. &nbsp是做什么用的呢，2.不做验证的话训练过程就是不eval吗，这样训练就看不到精度啦吧，如何得到精度指标呢？

**Comment by fxwfzsxyq** [comment]
是没有去做精度计算，这个逻辑没去实现，只是训练完之后用图片测试看效果



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] test这两个路径下应该是什么样的格式呢？test_file:  和  test_gt_path: 。另外想问下，多分类为什么没有DBProcessTestMLT 的函数，只有DBProcessTest (#46)





  
&amp;nbsp
   
&amp;nbsp是做什么用的呢，2.不做验证的话训练过程就是不eval吗，这样训练就看不到精度啦吧，如何得到精度指标呢？

**Comment by aishangmaxiaoming** [comment]
> 是没有去做精度计算，这个逻辑没去实现，只是训练完之后用图片测试看效果
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年7月7日(星期三) 上午10:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [BADBADBADBOY/pytorchOCR] test这两个路径下应该是什么样的格式呢？test_file: 和 test_gt_path: 。另外想问下，多分类为什么没有DBProcessTestMLT 的函数，只有DBProcessTest (#46) &amp;nbsp &amp;nbsp是做什么用的呢，2.不做验证的话训练过程就是不eval吗，这样训练就看不到精度啦吧，如何得到精度指标呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯嗯，那这两个指标是ACC:0.8428 | IOU:0.7523 ，代表什么呢？

**Comment by fxwfzsxyq** [comment]
这个是基于分割做的，所以会有像素的准确率和iou，具体计算方式 ptocr/utils/metrics.py




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] test这两个路径下应该是什么样的格式呢？test_file:  和  test_gt_path: 。另外想问下，多分类为什么没有DBProcessTestMLT 的函数，只有DBProcessTest (#46)





  
是没有去做精度计算，这个逻辑没去实现，只是训练完之后用图片测试看效果
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年7月7日(星期三) 上午10:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [BADBADBADBOY/pytorchOCR] test这两个路径下应该是什么样的格式呢？test_file: 和 test_gt_path: 。另外想问下，多分类为什么没有DBProcessTestMLT 的函数，只有DBProcessTest (#46) &amp;nbsp &amp;nbsp是做什么用的呢，2.不做验证的话训练过程就是不eval吗，这样训练就看不到精度啦吧，如何得到精度指标呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
嗯嗯，那这两个指标是ACC:0.8428 | IOU:0.7523 ，代表什么呢？

**Comment by aishangmaxiaoming** [comment]
> 这个是基于分割做的，所以会有像素的准确率和iou，具体计算方式 ptocr/utils/metrics.py
> […](#)

好的，谢谢大佬耐心解答
