### ISSUE TITLE
CRNN yaml配置中这个文件的数据格式是什么

### ISSUE THREAD

**Issue by yufanxin** [BADBADBADBOY/pytorchOCR#53]
key_file: /src/notebooks/MyworkData/EnglishCrnnData/key_new.txt
可以发一下参考的标准格式吗 谢谢

**Comment by fxwfzsxyq** [comment]
> key_file: /src/notebooks/MyworkData/EnglishCrnnData/key_new.txt
> 可以发一下参考的标准格式吗 谢谢

举个例子假设你只识别数字，那么这里面存储的就是0123456789这10个字符，这里面只有一行，不要有换行符

**Comment by yufanxin** [comment]
> 
> 
> > key_file: /src/notebooks/MyworkData/EnglishCrnnData/key_new.txt
> > 可以发一下参考的标准格式吗 谢谢
> 
> 举个例子假设你只识别数字，那么这里面存储的就是0123456789这10个字符，这里面只有一行，不要有换行符

好的谢谢回复解答，还有个问题，
trainload：
  train_file: ['/src/notebooks/MyworkData/EnglishCrnnData/train_lmdb/SynthText/','/src/notebooks/MyworkData/EnglishCrnnData/train_lmdb/MJSynth']

这里的格式能说明一下吗  
是file:   
         img
         gt
吗还是其它的格式？

**Comment by fxwfzsxyq** [comment]
这里存放的是lmdb格式的数据，需要使用script文件夹中的create_lmdb_multiprocessing.py文件生成




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月2日(星期四) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BADBADBADBOY/pytorchOCR] CRNN yaml配置中这个文件的数据格式是什么 (#53)





   
key_file: /src/notebooks/MyworkData/EnglishCrnnData/key_new.txt
 可以发一下参考的标准格式吗 谢谢
  
举个例子假设你只识别数字，那么这里面存储的就是0123456789这10个字符，这里面只有一行，不要有换行符
  
好的谢谢回复解答，还有个问题，
 trainload：
 train_file: ['/src/notebooks/MyworkData/EnglishCrnnData/train_lmdb/SynthText/','/src/notebooks/MyworkData/EnglishCrnnData/train_lmdb/MJSynth']
 
这里的格式能说明一下吗
 是file:
 img
 gt
 吗还是其它的格式？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
